
@endpoint =http://localhost:3001/api/v1


###
### POST Request for a user
## Expected result is ........
# @name postAUser
POST {{endpoint}}/users HTTP/1.1
content-type: application/json

{ "name" : "una3",
   "phonenumber" : "0871234567",
   "email" : "t1@mymail.iecom",
   "dob" : "2001/01/23",
   "silly": "this is not just silly but dangerous",
   "password" : "password10"
  }

###

POST {{endpoint}}/users HTTP/1.1
content-type: application/json

{ "name" : "una3",
   "phonenumber" : "0871234567",
   "email" : "test@test.ie",
   "dob" : "2001/01/23",
   "silly": "this is not just silly but dangerous",
   "password" : "testtest"
  }

###
# @name login
poST {{endpoint}}/auth HTTP/1.1
content-type: application/json

{ 
   "email" : "john.doe9ju@mymail.iecom",
   "password" : "password"
  }

###
@accessToken = {{login.response.body.accessToken}}



poST {{endpoint}}/auth HTTP/1.1
content-type: application/json

{ 
   "email" : "joe@mymail.iecom",
   "password" : "WRONGpassword"
  }
###



DELETE {{endpoint}}/users/adsfasf HTTP/1.1
content-type: application/json

#######

DELETE {{endpoint}}/users/adsfasf HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}