@endpoint =http://localhost:3000/api/v1/events

###
### POST Request for a event
## Expected result is ........
# @name postnEvent
POST {{endpoint}} HTTP/1.1
content-type: application/json

{
    "userId": "68d14e43cf8a9f42c91c5236",
    "title": "Class",
    "description": "Happens every week - it is fun",
    "date": 
       "202025-10-015T00:00:00Z"
    ,
    "location": "Beside the birds",
    "attendees": [
      {
        "name": "Attendee 1",
        "email": "attendee1@example.com",
        "rsvp": "no"
      },
      {
        "name": "Attendee 2",
        "email": "attendee2@example.com",
        "rsvp": "yes"
      },
      {
        "name": "Attendee 3",
        "email": "attendee3@example.com",
        "rsvp": "yes"
      },
      {
        "name": "Attendee 4",
        "email": "attendee4@example.com",
        "rsvp": "yes"
      },
      {
        "name": "Attendee 5",
        "email": "attendee5@example.com",
        "rsvp": "yes"
      }
    ]
  }

###


GET {{endpoint}}/68ec11abf55cd0c18263de28


###


    
POST {{endpoint}}/68ec11abf55cd0c18263de28/attendees HTTP/1.1
content-type: application/json

      {
        "name": "very new",
        "email": "attendee5@example2.com",
        "rsvp": "maybe"
      }

###

# valid ObjectID but not in events collection
POST {{endpoint}}/68d14e43cf8a9f42c91c5236/attendees HTTP/1.1
content-type: application/json

      {
        "name": "new now",
        "email": "attend@gmail.com",
        "rsvp": "maybe"
      }
