
@endpoint =http://localhost:3000/api/v1/users

###
### POST Request for a user
## Expected result is ........
# @name postAUser
POST {{endpoint}} HTTP/1.1
content-type: application/json

{ "name" : "{$ne : null}",
   "phonenumber" : "0871234567dfasfasf",
   "email" : "john.doe@mymail.ie",
   "dob" : "2001/01/12gfggggfsdg",
   "silly": "this is not just silly but dangerous"
  }
  
  
###

@newUserID = {{postAUser.response.headers.location}}

###
GET  {{endpoint}} HTTP/3.0
content-type: application/json

###
GET  {{endpoint}}?filter={"name":"John Doe"} HTTP/3.0
content-type: application/json

###
GET  {{endpoint}}?filter={"phonenumber":{"$regex":"087","$options":"i"}} HTTP/3.0
content-type: application/json

###
GET  {{endpoint}}/{{newUserID}} HTTP/1.1
content-type: application/json

###
DELETE  {{endpoint}}/6b18dc797b2dfcbe4 HTTP/1.1
content-type: application/json

###

PUT  {{endpoint}}/{{newUserID}} HTTP/1.1
 content-type: application/json

{
  "_id": "68d5a71c794c006be4c59014",
  "name": "New User10-jio",
  "phonenumber": "0871234567",
  "dob": "2002-01-01T00:00:00.000Z"
}
